### ISSUE TITLE
Struct ZomeCall not work

### ISSUE THREAD

**Issue by acscoder** [holochain/holochain-client-rust#4]
i used this crate ,tried to connect conductor but it not work , i got issues with Struct ZomeCall

**Comment by guillemcordoba** [comment]
Hi @acscoder, it's a bit hard to help you without more information. Could you share your code, and the error that shows up?

**Comment by acscoder** [comment]
> Hi @acscoder, it's a bit hard to help you without more information. Could you share your code, and the error that shows up?

i cloned code here https://github.com/holochain/happ-client-call-tutorial , js client worked but rust client not work , i tried debug and see we have issues with Struct ZomeCall , i can't make it work

It will error here because of mismatched types
// define the context of the request
    let api_request = ZomeCall {
        cell_id: cell_id.clone(),
        zome_name: ZomeName::from(String::from(ZOME_NAME)),
        fn_name: FunctionName::from(String::from(FN_NAME)),
        payload: encoded_payload,
        cap: None,
        provenance: cell_id.clone().agent_pubkey().to_owned(),
    };

**Comment by jost-s** [comment]
@acscoder A long time has passed. The mentioned tutorial has been deprecated and the clients have seen major updates. Please try again now and post again here if the problem persists.
