### ISSUE TITLE
Websocket Connections are disconnecting

### ISSUE THREAD

**Issue by zeeshan595** [holochain/holochain-client-rust#56]
The 0.4.x version of the client is not listening for signals which causes holochain to close the connection. 

Could we update the version of the client?

**Comment by jost-s** [comment]
@ThetaSinner There's this test, does it not cover enough? https://github.com/holochain/holochain-client-rust/blob/develop/tests/app.rs#L82

**Comment by jost-s** [comment]
@zeeshan595 Please always specify which version of Holochain you're referring to and also which exact version of the client.
